### ISSUE TITLE
Is it possible to pass custom sensors like tutorial 12 in a 1-axis analysis?

### ISSUE THREAD

**Issue by metavektor** [NREL/bifacial_radiance#263]
Hi again Bifacial Radiance team!

As my post title hints, I'm trying to make ground irradiance measurements like the ones in the APV tutorial 12 but using the 1-axis tracking workflow. As far as I can tell, the scan locations for the front and back of the PV surfaces are passed through the trackerdict, so the moduleAnalysis function isn't applicable here, or? Analysis1axis doesn't seem to be capable of this out of the box either.

Is there a way to change scan locations in the trackerdict? Is there potentially a way to append a custom scan location to 1axis scenes? If my questions are waaay far off, I hope you understand the problem statement and I'd be grateful for any help :)

Hope you've had a nice weekend.

**Comment by shirubana** [comment]
Hello :)

Yes, that makes total sense, and yes, we need to add that. I think I just pushed some changes into the development version that should do what you want, with the caveat that:

1) You must pass a frontscan and/or backscan dictionary that have the right parameters 
2) Frontscan and backscan (if you pass both, or if you pass 1 with the generated) must have the same number of sensors, else it will complain when saving results.

This mod will only sample the same spot for all times simulated though, will not vary with the angle, so it's ideal for sampling the ground for eample for the APV. Do you want to still scan on the module but shifted up and down? If that's the case on the lines I modified we have to pass ability to modify parameters of the calculated frontscan/backscan, instead of a whole new frontscan/backscan... Let me know. We have to think how to do both elegantly without adding too many parameters.
 
FYI The code I added is in ``analysis1axis`` function:

                frontscan, backscan = analysis.moduleAnalysis(scene=scene, modWanted=modWanted, rowWanted=rowWanted, sensorsy=sensorsy)
                if modscanfront is not None:
                         frontscan = modscanfront
                if modscanback is not None:
                        backscan = modscanback

**Comment by shirubana** [comment]
@metavektor my last push into the branch allows you to change any/all of the keys in the frontscan backscan to analysis1axis. Hope this helps! Closing the issue, this feature will be officially released in next release

**Comment by metavektor** [comment]
Hey hey, wow you're too fast for me! :) 

I ended up fudging a solution for my weird problem and essentially scripted static scenes with tilts read in through a for loop, which is definitely less than ideal but physically the same. It definitely sounds like you've added a functionality that will help avoid this! On the weekend I'll jump back in to test your addition out.

Thank you again for your time and awesome efforts!
