### ISSUE TITLE
Saving time doing only backscans

### ISSUE THREAD

**Issue by bnows** [NREL/bifacial_radiance#308]
Hi, everyone.
Sometimes I just need back irradiance (hourly) and therefor added a new variable in **AnalysisObj.analysis** and **AnalysisObj.analysis1axis** to just skip the frontscan if I don't need it.

![image](https://user-images.githubusercontent.com/75615642/117823189-7c359d80-b26d-11eb-82e0-14d15fb9dbda.png)

Works pretty well so far and saves about 20 second per simulated hour on my desktop PC.
Does anybody with a deeper insight in radiance/bifacial_radiance has further ideas how to save simulation time while doing only backscans?

**Comment by shirubana** [comment]
Hi bnows -- great implementation, sorry I hadn't seen your issue. We worked on this during summer so hopefully it'll be rolled into the next version.

'Accuracy' is by default set to low and can be changed to high, which increases time but not really accuracy, as at most simulations that is dictated already by the stochastic nature of the process, in which case it is better to run various simulatiosn and average them. But that doesn't reduce your time.

Besides making your scene as simple and representative of what you want, the next step is going to Cloud environments. Raytracing itself is a very computationally expensive process. Things to save time is doing gencumsky1axis instead of gendyalit1axis for tracking routines or just gencumsky for fixed routines, but then you can't do power hour-by-hour calculations or electrical mismatch, and  just evaluate things like bifacial gain and shading factors.

**Comment by shirubana** [comment]
We have implemented different front and back sensors, as well as sampling on X for full module sampling on the development branch, so closing the issue. Targetting this for the next release by end of the month.
