### ISSUE TITLE
readWeatherFile starttime and endtime inputs are ambiguous

### ISSUE THREAD

**Issue by cdeline** [NREL/bifacial_radiance#331]
This error pertains to the current development branch only.  To be consistent with YY_MM_DD_HH_MM timestamp options, we really should replace the starttime and endtime inputs with proper datetime or pd.TimeIndex options.  The previous method was to pass in a string in MM_DD_HH format, so if we're still going to accept that as an option, perhaps we should accept it for now but throw a deprecation warning and request proper datetime inputs moving forward.

**Comment by cdeline** [comment]
@shirubana:  So here's a strategy that I think will work.  I'll start on a pull request today, but I'd like to hear your thoughts.  
1) coerce_year is changed to a boolean and it's true by default.
2) the actual year the metdata is coerced to (coerce_year_val) is set based on the YY passed in by startdate. If blank, set to 2001 by default.
3) switch to less-ambiguous timestamp strings:  yyyy-mm-dd_HHMM.  These are easily split and parsed unambiguously.  We can still allow a mm_dd_HH option, possibly with a deprecation warning, but it's quickly converted to the above string.
4) possibly allow datetime.datetime type inputs as well.  These work particularly well for real field data.  But modelchain and GUI will stick to string values for these.
5) error conditions to check for.  The default assumption is that TMY data inputs can be coerced, and real data should have startdates with meaningful year information:
 -- if no year information is passed in startdate, set coerce_year to True, even if passed as false.
 -- if start and enddate are more than 366 days apart, then set coerce_year to False even if it's passed as true.
 -- What happens if you try to coerce to a year with a leap day in it, like 2020?  I think it may work out ok, but we should test with both real data (366 days) and TMY data (365 days).

**Comment by shirubana** [comment]
Why 2001 and not 2021?

I was catering to the GUI as well as some sort of back compatibility with keeping the string format. Maybe doing the datetime is going to solve the issue of not passing year but passing time. The issue is that, if they pass strings of different lenghts -- are they passing the left end or the right end? i.e. , year, or minute? We have to make sure that minute resolution is kept.

I already have the leap year function for leap years, that removes Feb. 29 so it works. Its handled in _saveTempTMY. The changes you need and are suggesting with htis pull request is mostly for how startime and endtime are handled. 

I honestly don't know how much time you have to do all of this, I guess now that everything is more centralized it should be easier.  The current changes work and are not far enough from previous version, and I need to focus on other improvements for Soltec. Should we talk about prioritization?

**Comment by shirubana** [comment]
Sorry ~ didn't mean to be so neg. I just want to Keep it Simple, and make it work for the primary users which are us -- Matt and I have ben using the Year and Minute format to be able to handle field data for the BEST field and make our life easiers ~ anything will work. Thanks for helping with this

**Comment by cdeline** [comment]
This is fixed now in release 0.4.0.
