### ISSUE TITLE
Issues with startime format mm_dd_hh on readWeatherFile

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#439]
First identified TMY3 subhourly format failing on readEPWWeatherFile

simulation_D8.ini

[timeControlParamsDict]
starttime = 06_21_12
endtime = 06_22_12

weatherFile = C:\Users\sayala\Documents\GitHub\bifacial_radiance\tests\Custom_WeatherFile_TMY3format_15mins_2021_wTrackerAngles_BESTFieldData.csv

![image](https://user-images.githubusercontent.com/22824806/195125733-e15f3b72-3e7f-40d0-9da8-903024159a90.png)

**Comment by shirubana** [comment]
starttime format causing funny things in Solargis as well,. maybe related to #439  ?
Accroding to documentation

        starttime : str
            Limited start time option in 'YYYY-mm-dd_HHMM' or 'mm_dd_HH' format

Dont work

[timeControlParamsDict]
starttime = 06_21_1130
endtime = 06_22_1230

[timeControlParamsDict]
starttime = 06_21_11
endtime = 06_22_12

[timeControlParamsDict]
starttime = 06_21
endtime = 06_22

simulation D9 testing with solargis in the test folder:

WORKS:
[timeControlParamsDict]
starttime = 2020-06-21_1130
endtime = 2020-06-22_1230

[timeControlParamsDict]
starttime = 2020-06-21_11
endtime = 2020-06-22_12

[timeControlParamsDict]
starttime = 2020-06-21
endtime = 2020-06-22

**Comment by jaivik1** [comment]
I tried reading Solargis TMY file however, it somehow not parsing the info correctly and gives the error message. 
I found a way-out by creating TMY3 from solargis and it worked.

![image](https://user-images.githubusercontent.com/65771969/217463578-2a876e69-e96c-415a-8f90-5405b136b472.png)

**Comment by cdeline** [comment]
If anyone else gets this error `ValueError: invalid literal for int() with base 10:`.  This error is coming from within pvlib.read_tmy3.  It appears to be due to reading the 'Time (HH:MM)' column as literally HH:MM, but in our test file we have time entries like '2:30' (without the leading zero).  I've fixed this by re-saving this 15-minute test file with `data['HH:MM'].str.zfill(5)` to make sure it reads '02:30' etc.  Now it's working.  I've added this weather csv file to our test matrix.  Anyone else who gets this error: check to make sure you have leading zeros on your time data.
