### ISSUE TITLE
module Object functionality in multiple-folder simulations

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#463]
Not sure if an issue just a quirk, but wanted to keep track of it

When creating a module object and then going to parallelization or various simulations that use various folders, if you pre-created the module object on the login node if you pass it as an object it fails, but if you pass just the name as a string it succeeds

![image](https://user-images.githubusercontent.com/22824806/228534847-2f51fb91-d52b-4a8d-b0d2-00e0579ad972.png)
where
```
basicmodule = radObj.makeModule(name='basicModule', x=1, y=2)
```

This is because when passing the module object it looks for its path location in the relative `\objects` folder of the simulation, which in the parallel simulation it is empty. Whereas when you pass just the text name it recreates the .rad module file when running makescene fresh.

![image](https://user-images.githubusercontent.com/22824806/228534562-904252fc-3a8f-4d0b-9e0a-559eaf6ed74f.png)

S.

**Comment by cdeline** [comment]
Setting hpc=True might fix this because it uses the full directory path when addressing the objects.  Of course, you would have to update the path setting in the .rad object to point to where you move it to, if it's created in one directory and moved to another.  But yes, in general the radiance objects should be kept in the directory where they are created.  the relative paths tend to be defined based on the root of the project directory defined when you first created the RadianceObject.
