### ISSUE TITLE
'got an unexpected keyword argument 'hpc' in 'AgriPV - Coffee Plantation with Tree Modeling.py'

### ISSUE THREAD

**Issue by yw567** [NREL/bifacial_radiance#472]
Hi there,

Thanks for your effort in this toolkit. 

Recently, when I tried to run the example code 'AgriPV - Coffee Plantation with Tree Modeling.py', I met a bug : TypeError: makeScene() got an unexpected keyword argument 'hpc' as shown below.
![image](https://github.com/NREL/bifacial_radiance/assets/130709822/e9c5ba1a-41a5-4965-a000-41f40d421bd1)

 I ran it in Windows system, did I miss something? I noticed that in installment guidance, it indicated the associated softwares needed for Windows may be slightly out of date. Could it be a version issue? 

I'll appreciate it if you can provide some suggestions or help.

Sincerely

**Comment by shirubana** [comment]
I probably havent updated the journal for the latest bifacial_Radiance journal. The HPC input is now taken only when you create the RadianceObj and the AnalysisObj, and then it just remembers throughout. I.e.:

>> RadianceObj(name=’My_simulation’, path=folderforresults, hpc = False) 

All the flag does is give a couple more seconds when searching for created files so it doesn’t fail because of the parallelized read/write. So having it as False is okay specially for windows runs; you could just remove “hpc” input to that function on the journal and it should run. 

I will hopefully update the journal itself soon 😊 thanks for pointing that out

**Comment by cdeline** [comment]
This has been fixed by v0.4.3 or v0.4.4
