### ISSUE TITLE
Tutorial1: warning during linescan

### ISSUE THREAD

**Issue by lherrero01** [NREL/bifacial_radiance#476]
Hi,

I'm getting started on bifacial_radiance and, after completing the installation, I get the following issue during the linescan, after generating the oct file:

![Captura](https://github.com/NREL/bifacial_radiance/assets/145660359/e8a5e0b8-896a-4fb2-bbaa-ee5879bdf704)

I have already checked that:

-  Radiance\bin is on my system variable PATH
- rtrace.exe file is located on the Radiance\bin
- raynit.cal is located on the Radiance\lib

**Comment by shirubana** [comment]
Hi! Welcome and thanks for the question. 
Can you try adding the lib folder to the path as well? That's where rayinit.cal is located at

**Comment by lherrero01** [comment]
Hi, I have added the lib folder to the path, but I still get the same error.

**Comment by shirubana** [comment]
which version of radiance, operating system do you have?

**Comment by lherrero01** [comment]
I'm using the latest official release, Radiance 5.3 (2020-09-03) on Windows 10.

**Comment by lherrero01** [comment]
I have them on System Variables.

**Comment by cdeline** [comment]
If this hasn't been fixed so far, it should otherwise be taken care of by #533 when we finish that up.
If anyone else is seeing this error, the following should take care of it.  (instructions for Windows machines)
Going to your system environmental variables (in System control panel > system > advanced > environment variables) , make sure that RAYPATH includes both the current directory ( "." ) and the \lib\ folder of RADIANCE 
Something like:
`RAYPATH=.;C:\Radiance\lib;`
Likewise, the PATH variable needs to include the RADIANCE binaries
`PATH= <other stuff> ;C:\Radiance\bin; <other stuff>`
