### ISSUE TITLE
gendaylit - normRGB

### ISSUE THREAD

**Issue by Funerus** [NREL/bifacial_radiance#506]
Hey everyone,

I've been going through the _gendaylit_ command as defined within the main code of bifacial_radiance. 

Specifically, when defining the ground glow for each wavelength channel, the reflectance of each channel is normalized with normval = R*.263 + G*.655 + B.082 leading to:
skyfunc glow ground_glow
0
0
4 R/normval G/normval B/normval 0

Since I am interested in solar irradiance and not illuminance, do I still need to normalize each RGB reflectance value?

Regardless, by default the sky is defined to be grey, so I would assume that normalizing ground reflectance is unnecessary? 

Any insights are highly appreciated,
Cheers,
Alex

**Comment by cdeline** [comment]
Hi Alex (sorry for the delay)

I'm sorry that we're not going to be the best ones to give you an authoritative answer on this question.  I would refer to the [gendaylit man pages](https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gendaylit.pdf) where this topic is discussed.  I believe that the treatment of irradiance in this way is self-consistent because the definition of the sky brightness is in Wm-2, and the measurement of incident irradiance is in Wm-2.  My recollection was that defining the ground glow based on this default illuminance value will allow calculation back to Wm-2 using Radiance's default white light efficacy of 179 lm/W.

**Comment by cdeline** [comment]
I'm going to close this issue as resolved - please reply back if it should be reopened.
