### ISSUE TITLE
Desired behaviour, coerce_year = None

### ISSUE THREAD

**Issue by shirubana** [NREL/bifacial_radiance#526]
![image](https://github.com/user-attachments/assets/483ff59c-7392-4b15-b6b6-0111ea604028)

Setting coerce_year to None, still coerces the year to 2021 (line 860 in _parseTimes
It seems this should not be coerced?

S.

**Comment by cdeline** [comment]
This is desired behavior for 8760 TMY data.  Mainly because if you look at an actual TMY file, each month has a different year that it came from, so it's impossible to filter on date.  If you have 8760 data, you need to coerce to some sort of year.  if you pass a starttime with a year in it, it will default to coercing to that year.  if you don't, it defaults to 2021.  Note that non-8760 data which is presumably measured will not have this behavior.  and if your dataset spans multiple years, it will prevent you from coercing.
This is from `def _saveTempTMY`:
>
        if len(tmydata) == 8760: 
            print("8760 line in WeatherFile. Assuming this is a standard hourly"+
                  " WeatherFile for the year for purposes of saving Gencumulativesky"+
                  " temporary weather files in EPW folder.")
            if coerce_year is None and starttime is not None:
                coerce_year = starttime.year
            # SILVANA:  If user doesn't pass starttime, and doesn't select
            # coerce_year, then do we really need to coerce it?
            elif coerce_year is None:
                coerce_year = 2021                
            print(f"Coercing year to {coerce_year}")

**Comment by cdeline** [comment]
OK, I'll check it out.
